const {topic}=require('./new40-content.cjs');
topic(41,{
summary:['Metrics Server supplies recent resource usage through the resource metrics API.','Prometheus collects time-series measurements from configured targets.','Grafana queries data sources to display dashboards and support alerting workflows.','Useful monitoring connects infrastructure signals with application outcomes.'],
cue:'Measure, retain, display, respond.',
plain:'Maya checks today’s counter occupancy, keeps a history of busy hours, and draws a chart. A current reading, a notebook of readings, and a chart are different tools.',
story:'The catalog exposes a small /metrics file. We fetch its teaching gauge, compare resource requests with optional live usage, and explain where an existing monitoring stack would collect it.',
detail:'A scrape target must be reachable and configured; adding an HTTP endpoint does not make Prometheus discover it. Metrics Server is not a long-term application metrics store. A dashboard can show missing or stale data while the application still runs, so inspect freshness and collection errors.\n\nFor a real shop, connect request rate, error rate, and latency to stock/search/checkout outcomes. Bound label cardinality: customer IDs and request IDs usually do not belong on every metric. The fixed catalog gauge in this example does not measure traffic or capacity.',
source:'[Kubernetes observability](https://kubernetes.io/docs/concepts/cluster-administration/observability/), [Prometheus concepts](https://prometheus.io/docs/concepts/data_model/)',
guide:'Files: [page and metric](../../manifests/10-page.yaml), [Deployment](../../manifests/20-deployment.yaml), and [scrape reference](reference/prometheus-scrape.yaml).\n\nThe ConfigMap key §metrics§ becomes §/www/metrics§. HELP describes the measurement; TYPE declares a gauge; §bookshop_catalog_titles 60§ is one fixed sample. The Service exposes it at §/metrics§ on port 80.\n\nThe reference sets §job_name: bookshop-platform§, a 30-second scrape interval, the metrics path, and one namespace-qualified Service target. It is Prometheus configuration, not Kubernetes resource YAML. A monitoring owner must integrate it with their existing setup; controllers using ServiceMonitor discovery have a different configuration path. The Deployment’s requests/limits remain scheduling/runtime declarations, not measurements.',
runbook:'## Prerequisites\n\nStart the base. Resource usage checks need a working metrics API; historical queries need an already configured monitoring system.\n\n~~~powershell\nkubectl -n k8s-learning-platform exec deployment/platform-catalog -- wget -T 3 -qO- http://platform-catalog/metrics\nkubectl -n k8s-learning-platform get deployment platform-catalog -o yaml\nkubectl top pods -n k8s-learning-platform\n~~~\n\nExpect the gauge value 60 from HTTP. If top reports unavailable metrics, record that dependency as skipped; the HTTP check can still pass. Compare requests with usage only when real values are returned.\n\n## Optional collection proof\n\nIn the existing Prometheus UI, inspect the configured target and query §bookshop_catalog_titles§. Check its job/instance labels and sample time. A successful manual fetch does not prove scraping or retention. Use Grafana only after verifying its data source returns that series.\n\n## Troubleshooting and cleanup\n\nAn HTTP failure needs Service/endpoints/routing checks. A missing series needs target discovery, permissions, scrape logs, and time-range checks. No monitoring add-on is installed or edited here, so there is no topic resource to remove.'});
topic(42,{
summary:['Applications should emit useful events to stdout and stderr.','Kubelet and runtime logging provide local, limited log access.','Collectors forward logs to searchable storage with retention rules.','Correlation fields connect individual events across components.'],
cue:'Write locally, ship centrally, correlate deliberately.',
plain:'Each counter keeps a receipt roll. A central filing service collects those rolls so Maya can find a transaction after the counter has been replaced.',
story:'A one-shot catalog Job writes three structured events, including a warning to stderr. We inspect them with kubectl and identify the fields a collector would preserve.',
detail:'Fluent Bit can run as a node-level collector, while systems such as Elasticsearch/Kibana or Loki/Grafana provide different storage/query approaches. Select a stack by query needs, retention, access, and measured cost; one backend is not universally cheaper or faster.\n\nCentralization needs working collection, storage, and access controls. Logs from an already deleted Pod are not guaranteed through kubectl. Avoid credentials and unnecessary personal data in events, and remember that stdout/stderr interleaving is not a reliable distributed ordering mechanism.',
source:'[Kubernetes logging architecture](https://kubernetes.io/docs/concepts/cluster-administration/logging/), [Fluent Bit Kubernetes guide](https://docs.fluentbit.io/manual/installation/kubernetes)',
guide:'File: [catalog log Job](manifests/10-log-job.yaml).\n\n§batch/v1§ Job §catalog-log-demo§ uses §backoffLimit: 0§ and §restartPolicy: Never§ so the example runs once without automatic retries obscuring the event sequence. Each echo writes JSON with §level§, §event§, and the harmless shared §request_id: lesson-42§. §>&2§ sends the warning to stderr.\n\nThe template label §exercise: logs-42§ supports scoped discovery. Kubernetes stores the Pod’s container log; it does not automatically ship these lines to a central backend. No collector DaemonSet is installed, and the Job creates no external log destination.',
runbook:'## Prerequisites\n\nUse the shared namespace and permission for Jobs and logs. Central search additionally needs an existing collector/backend.\n\n~~~powershell\nkubectl apply -f topics/42-centralized-logging/manifests/\nkubectl -n k8s-learning-platform wait --for=condition=Complete job/catalog-log-demo --timeout=120s\nkubectl -n k8s-learning-platform logs job/catalog-log-demo --timestamps=true\nkubectl -n k8s-learning-platform get pods -l exercise=logs-42\n~~~\n\nExpect catalog_started, supplier_delayed, and catalog_complete events with the same request ID. The warning does not make the Job fail; its process exits successfully.\n\n## Optional central proof\n\nSearch the existing backend for this namespace and request ID. Compare message fields, Pod identity, timestamp, and any collector-added metadata. If absent, the local log proof still stands but central collection is unverified.\n\n## Troubleshooting and cleanup\n\nA failed startup needs Pod events before log analysis. Missing central events need collector routing and retention checks. Capture only the harmless lab evidence before cleanup.\n\n~~~powershell\nkubectl delete -f topics/42-centralized-logging/manifests/ --ignore-not-found\n~~~\n\nDelete/recreate this Job for another run; editing a completed Job does not rerun it.'});
topic(43,{
summary:['Blue-green keeps two releases available and changes which one receives new traffic.','Canary exposes a new release to a limited portion of traffic first.','Replica-based Service selection provides an approximate split, not precise request weighting.','Promotion requires application evidence and a tested recovery path.'],
cue:'Switch all, or sample first.',
plain:'Maya can redirect the entrance to a second prepared counter area, or invite a small group to try the new counter while most visitors keep using the old one.',
story:'This question reconnects to the existing blue-green and canary labs. The learner uses their pages and Service selectors, then adds explicit success and rollback criteria.',
detail:'Readiness and capacity must be sufficient before promotion. Existing connections can outlive a Service selector change. A weighted traffic router still produces a statistical distribution over requests; a small sample need not match its configured percentage exactly.\n\nThe deployment strategy does not solve incompatible database changes or irreversible external side effects. Compare error rate and latency against a useful baseline and sample window, and decide who can stop the release. Automated progressive delivery returns in question 79.',
source:'[Kubernetes Services](https://kubernetes.io/docs/concepts/services-networking/service/), [Argo Rollouts canary concepts](https://argo-rollouts.readthedocs.io/en/stable/features/canary/)',
guide:'Reuse the [blue-green manifest guide](../../../02-blue-green-deployment/manifest-guide.md) and [canary manifest guide](../../../03-canary-deployment/manifest-guide.md).\n\nThe blue-green Service’s selector chooses one release label; its two Deployments have distinct identities. The canary Service selects both stable and canary Pods, while their replica counts affect the available endpoints. Their ConfigMaps make the served version visible.\n\nThese examples already have independent namespaces and full YAML explanations, so this question adds no duplicate manifests. A Service port-forward attaches to one Pod and cannot prove the traffic distribution. Follow the existing runbooks’ in-cluster request tests.',
runbook:'## Prerequisites\n\nUse the intended practice context and the dependencies in the existing release labs. Run one at a time.\n\n~~~powershell\ncd ../02-blue-green-deployment\n~~~\n\nFollow its [runbook](../../../02-blue-green-deployment/runbook.md), including the traffic switch, version proof, rollback, and cleanup. Then:\n\n~~~powershell\ncd ../03-canary-deployment\n~~~\n\nFollow its [runbook](../../../03-canary-deployment/runbook.md), including repeated requests and cleanup. Return afterwards:\n\n~~~powershell\ncd ../05-bookshop-platform\n~~~\n\n## Expected result\n\nExplain which selector/replica change caused each result. Record a promotion threshold, observation window, and rollback trigger for a hypothetical real catalog. A few successful requests are not enough to establish an error-rate target.\n\n## Troubleshooting and cleanup\n\nUse each lab’s endpoint, readiness, and selector checks if the wrong page appears. Complete both existing cleanup procedures; this question creates no additional objects.'});
topic(44,{
summary:['ResourceQuota constrains aggregate namespaced resource usage or object counts.','LimitRange can default and constrain individual resource requests and limits.','Admission evaluates new objects against applicable limits and quota.','Namespace budgets complement capacity planning and do not create physical isolation.'],
cue:'LimitRange sizes each counter; quota budgets the branch.',
plain:'Maya limits the size of each counter and the total number of counters in a small practice room. Both rules matter: small counters can still fill the room if there are too many.',
story:'Two Pods receive default requests and limits in a separate budgets namespace. A too-large Pod and a third Pod are submitted only as server dry-runs to distinguish the two controls.',
detail:'Defaults affect admitted Pods; they do not retroactively resize every running Pod. Quota usage can take a moment to settle. CPU requests, limits, and object count are different accounting dimensions.\n\nA namespace boundary and quota do not guarantee performance isolation, security isolation, or a fair share of every node. Leave headroom for rollouts, system work, and terminating resources. The teaching quota is intentionally tiny and belongs only to this disposable namespace.',
source:'[ResourceQuota](https://kubernetes.io/docs/concepts/policy/resource-quotas/), [LimitRange](https://kubernetes.io/docs/concepts/policy/limit-range/)',
guide:'Files: [namespace](manifests/00-namespace.yaml), [LimitRange](manifests/10-limitrange.yaml), [quota](manifests/20-quota.yaml), [first Pod](workloads/budget-one.yaml), [second Pod](workloads/budget-two.yaml), [too-large input](negative/too-large.yaml), and [extra-Pod input](negative/budget-extra.yaml).\n\nLimitRange defaults each container to requests §25m/32Mi§ and limits §100m/64Mi§. Its maximum is §200m/128Mi§. The quota allows only two Pods, alongside CPU/memory totals. The two ordinary inputs omit resources deliberately so admission can add defaults.\n\nThe too-large input asks for §250m§ CPU and a §300m§ limit, exceeding the per-container maximum. The extra Pod fits the per-container rules but becomes the third Pod after the two actual workloads exist. Keep both negative inputs out of apply commands.',
runbook:'## Prerequisites\n\nPermission for a fresh §k8s-learning-budgets§ namespace, LimitRange, quota, and Pods. Inspect any existing namespace before using it.\n\n~~~powershell\nkubectl get namespace k8s-learning-budgets\nkubectl apply -f topics/44-quotas-and-limitranges/manifests/00-namespace.yaml\nkubectl apply -f topics/44-quotas-and-limitranges/manifests/\nkubectl apply -f topics/44-quotas-and-limitranges/workloads/budget-one.yaml\nkubectl -n k8s-learning-budgets get pod budget-one -o yaml\nkubectl apply --dry-run=server -f topics/44-quotas-and-limitranges/negative/too-large.yaml\n~~~\n\nExpect default resources on budget-one and a LimitRange rejection for the oversized input. Then:\n\n~~~powershell\nkubectl apply -f topics/44-quotas-and-limitranges/workloads/budget-two.yaml\nkubectl -n k8s-learning-budgets describe resourcequota counter-budget\nkubectl apply --dry-run=server -f topics/44-quotas-and-limitranges/negative/budget-extra.yaml\n~~~\n\nExpect Pod usage 2 and a quota rejection. Both negative commands should exit nonzero for the stated reason; an unrelated permission error is not proof.\n\n## Recovery and cleanup\n\nInspect policy values and quota usage if observations differ. Do not raise the limits just to make the failure inputs pass. After inspecting ownership and contents:\n\n~~~powershell\nkubectl -n k8s-learning-budgets get pods,limitrange,resourcequota\nkubectl delete namespace k8s-learning-budgets\n~~~'});
topic(45,{
summary:['Pods receive network identities and share a network namespace among their containers.','A CNI implementation configures container networking for the node runtime.','Service routing and network-policy enforcement depend on the installed networking stack.','Reachability also depends on routing, addresses, policy, and the application listener.'],
cue:'Pod address, network path, Service front door.',
plain:'A counter has an address, corridors connect counters, and a reception desk directs visitors. Knowing the address does not prove the corridor is open or the counter is listening.',
story:'Maya compares the catalog Service IP with its Pod IPs, resolves the Service name, and tests an actual request. The learner identifies the installed network provider without replacing it.',
detail:'The Kubernetes networking model expects Pod communication without requiring application-managed address translation, while policy can restrict permitted traffic. Overlay, routed, and cloud-integrated implementations make different tradeoffs. Some stacks replace kube-proxy’s Service handling; do not infer the CNI from the presence of one familiar Pod name.\n\nCalico, Cilium, cloud CNIs, and Flannel-based arrangements have different capabilities and integrations. Verify the installed version/configuration for policy support, IP limits, and observability instead of treating a product name as a guarantee.',
source:'[Kubernetes network model](https://kubernetes.io/docs/concepts/services-networking/), [network plugins](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/)',
guide:'Read the [Deployment](../../manifests/20-deployment.yaml) and [Service](../../manifests/30-service.yaml).\n\n§containerPort: 8080§ documents the HTTP port; the process actually listens because its command starts httpd there. The Service’s §port: 80§ and §targetPort: http§ describe forwarding to those Pod listeners. The cluster assigns Service and Pod addresses; the manifests do not hardcode them.\n\nNo CNI manifest is supplied. Installing another network provider is a cluster-wide change, not a repair for one failed request. NetworkPolicy is revisited in question 75 with real allow/deny traffic checks.',
runbook:'## Prerequisites\n\nRun the base. Node/system-component inspection is optional and requires read permission.\n\n~~~powershell\nkubectl -n k8s-learning-platform get pods -l app=platform-catalog -o wide\nkubectl -n k8s-learning-platform get service platform-catalog -o wide\nkubectl -n k8s-learning-platform exec deployment/platform-catalog -- cat /etc/resolv.conf\nkubectl -n k8s-learning-platform exec deployment/platform-catalog -- nslookup platform-catalog\nkubectl -n k8s-learning-platform exec deployment/platform-catalog -- wget -T 3 -qO- http://platform-catalog\n~~~\n\nExpect Pod addresses distinct from the Service address, name resolution, and the platform page. These observations demonstrate this path, not every cross-node route.\n\n## Provider evidence\n\nUse the platform’s network documentation and, if permitted, inspect §kubectl -n kube-system get daemonsets§. Record the actual provider and whether Service routing and policy enforcement use the same component.\n\n## Troubleshooting and cleanup\n\nSeparate DNS failure, empty endpoints, blocked traffic, and an absent listener. A working localhost response alone does not prove Pod-to-Pod networking. All commands are reads, so there is no topic cleanup.'});
