const fs = require('fs');
const path = require('path');
const root = path.resolve('kubernetes-learning-lab');
const chapters = [
 {dir:'07-production-incidents',title:'Production Incident Clinic',range:'81–95',topics:[
 ['81','node-notready','Node NotReady: isolate the failure before evicting workloads','Node health, kubelet heartbeats, pressure signals, and safe cordon/drain decisions.','https://kubernetes.io/docs/concepts/architecture/nodes/'],
 ['82','service-no-endpoints','Service has no endpoints: prove selector, readiness, and port alignment','A repeatable path from Service selectors to EndpointSlices and Pod readiness.','https://kubernetes.io/docs/concepts/services-networking/service/'],
 ['83','rollout-stuck','Deployment rollout stuck: distinguish readiness, capacity, and disruption blockers','How to read rollout status, ReplicaSets, PDBs, and scheduler events before changing replicas.','https://kubernetes.io/docs/concepts/workloads/controllers/deployment/'],
 ['84','pvc-pending','PVC pending: classify storage class, binding mode, and provisioning failures','StorageClass, CSI, topology, and WaitForFirstConsumer diagnostics.','https://kubernetes.io/docs/concepts/storage/persistent-volumes/'],
 ['85','oomkilled','OOMKilled: account for the whole container memory footprint','Why heap-only reasoning misses native memory, page cache, and process trees.','https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'],
 ['86','rolling-503','Rolling update returns 503: make shutdown and readiness cooperate','PreStop, termination grace, readiness transition, and endpoint removal.','https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/'],
 ['87','dns-race','DNS race or intermittent lookup failures inside Pods','Search paths, CoreDNS capacity, conntrack, and node-local caching.','https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/'],
 ['88','etcd-full','etcd database full: recover safely before writes stop','Quota alarms, compaction, defragmentation, and key-size hygiene.','https://etcd.io/docs/v3.5/op-guide/maintenance/'],
 ['89','secret-leak','Secret accidentally exposed in logs: contain, rotate, and scrub','Immediate credential rotation plus log retention and audit review.','https://kubernetes.io/docs/concepts/configuration/secret/'],
 ['90','operator-upgrade','Cluster upgrade breaks CRDs or operators','Compatibility order: APIs, CRDs, operators, then workloads.','https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/'],
 ['91','hpa-flapping','HPA flapping: stabilize scale-up and scale-down','HPA behavior policies, stabilization windows, and good metrics.','https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/'],
 ['92','eviction-disk','Pod evicted for disk pressure: reclaim space without data loss','Ephemeral storage accounting, image garbage collection, and durable volumes.','https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/'],
 ['93','ingress-502','Ingress returns 502 after deployment','Readiness, Service targetPort, endpoints, and controller logs.','https://kubernetes.io/docs/concepts/services-networking/ingress/'],
 ['94','networkpolicy-cross-namespace','Cross-namespace traffic blocked after NetworkPolicy','Namespace selectors and additive ingress rules.','https://kubernetes.io/docs/concepts/services-networking/network-policies/'],
 ['95','statefulset-terminating','StatefulSet Pod stuck terminating','Finalizers, volume detach, grace periods, and force-delete risks.','https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/']
 ]},
 {dir:'08-production-governance',title:'Production Governance and Recovery',range:'96–110',topics:[
 ['96','cluster-cost','Cluster costs spike unexpectedly','Right-sizing, idle resource detection, and ownership attribution.','https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'],
 ['97','namespace-finalizer','Namespace deletion stuck on finalizers','Find remaining objects, repair controller-owned finalizers, and verify cleanup.','https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/'],
 ['98','admission-outage','Admission webhook outage blocks every deployment','Scope, timeout, failurePolicy, and emergency recovery for webhooks.','https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/'],
 ['99','certificate-expired','Certificate expired: kubelet cannot talk to the API server','Detect, renew, approve, and replace affected node or control-plane certificates.','https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/'],
 ['100','pdb-drain','Node drain kills too many replicas despite a PDB','Selector correctness, eviction API, anti-affinity, and unhealthy replicas.','https://kubernetes.io/docs/concepts/workloads/pods/disruptions/'],
 ['101','api-overload','API server overloaded: slow kubectl and controller loops','Request latency, noisy clients, APF, and etcd I/O.','https://kubernetes.io/docs/concepts/cluster-administration/flow-control/'],
 ['102','external-dns','Pod resolves cluster DNS but not external DNS','CoreDNS forwarding, egress policy, node resolver, and firewall checks.','https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/'],
 ['103','helm-stuck','Helm release stuck in pending-upgrade','Inspect release history, rollback, and recover orphaned release state.','https://helm.sh/docs/helm/helm_rollback/'],
 ['104','pv-mixup','Production mounts data from staging','PV reclaim policy, labels, StorageClasses, and restore validation.','https://kubernetes.io/docs/concepts/storage/persistent-volumes/'],
 ['105','cronjob-flood','CronJob creates thousands of completed Pods','History limits, TTL-after-finished, concurrency policy, and cleanup.','https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/'],
 ['106','psa-enforcement','Pod Security Admission rejects a workload','Namespace labels, securityContext, exemptions, and dry-run rollout.','https://kubernetes.io/docs/concepts/security/pod-security-admission/'],
 ['107','upgrade-safety','Upgrade a cluster safely with a rollback plan','Version skew, deprecated APIs, backups, staging, and controlled rollout.','https://kubernetes.io/releases/version-skew-policy/'],
 ['108','node-drain-pdb','Node drain cannot evict a Pod because of PDB','Eviction status, replica placement, unhealthyPodEvictionPolicy, and recovery.','https://kubernetes.io/docs/concepts/workloads/pods/disruptions/'],
 ['109','resource-quota','Namespace quota blocks a new workload','Quota usage, requests versus limits, and accurate workload accounting.','https://kubernetes.io/docs/concepts/policy/resource-quotas/'],
 ['110','nonroot-enforcement','Container runs as root despite a non-root policy','Pod Security Standards, image USER, runAsUser, and admission ordering.','https://kubernetes.io/docs/concepts/security/pod-security-standards/']
 ]}
];
const mkdir=p=>fs.mkdirSync(p,{recursive:true}); const write=(p,s)=>{mkdir(path.dirname(p));fs.writeFileSync(p,s.trimStart()+'\n');};
for(const ch of chapters){const cd=path.join(root,ch.dir);mkdir(path.join(cd,'topics'));
write(path.join(cd,'README.md'),`# ${ch.title}\n\nQuestions **${ch.range}** turn production symptoms into safe Kubernetes investigations. Each topic has a lesson, walkthrough, and reversible runbook.\n\n## Topics\n\n${ch.topics.map(t=>`- [${t[0]} ${t[1]}](topics/${t[1]}/lesson.md) — ${t[2]}`).join('\n')}\n\nStart with the [chapter story](story.md), then use the [manifest guide](manifest-guide.md) and [runbook](runbook.md).`);
write(path.join(cd,'story.md'),`# ${ch.title}: a production shift\n\nYou are the on-call engineer for the Bookshop platform. A page arrives with a symptom, not a root cause. Work from evidence: describe the object, inspect events and conditions, check controllers and dependencies, then make the smallest reversible change.\n\nThese questions cover ${ch.range}. Capture the before-state, prefer dry-run or read-only inspection, and verify recovery after the fix.`);
write(path.join(cd,'manifest-guide.md'),`# ${ch.title}: manifest and command guide\n\nUse live object state and server-side validation:\n\n\`\`\`powershell\nkubectl apply --dry-run=server -f example.yaml\nkubectl describe pod <pod>\nkubectl get events --sort-by=.lastTimestamp\n\`\`\`\n\nKeep production changes in version control. Save the before-state, make one bounded change, and compare the after-state.`);
write(path.join(cd,'runbook.md'),`# ${ch.title}: common response loop\n\n1. Record the alert, namespace, object name, and first observed time.\n2. Read status, conditions, events, logs, and dependency health.\n3. Check whether a recent rollout, policy, quota, node, or storage change explains the symptom.\n4. Apply the smallest reversible fix, then verify readiness, traffic, and error rate.\n5. Capture the root cause and prevention follow-up.\n\nNever force-delete a stateful or policy-protected object until ownership, data safety, and replacement capacity are understood.`);
for(const [n,slug,title,summary,url] of ch.topics){const td=path.join(cd,'topics',slug);mkdir(td);
write(path.join(td,'lesson.md'),`# ${n}. ${title}\n\n## Concise technical summary\n\n1. ${summary}\n2. Start with read-only evidence: status, conditions, events, logs, and related resources.\n3. Separate the immediate mitigation from the durable prevention.\n4. Verify recovery and record what changed.\n\nMemory cue: observe, classify, repair, verify.\n\n## Plain meaning\n\nTreat the alert like a bookshop shift handoff: identify which part of the store is failing, protect customer traffic, and only then repair the underlying shelf, door, or delivery route.\n\n## Step-by-step response\n\n1. Capture the object and dependencies with \`kubectl describe\`, \`kubectl get events --sort-by=.lastTimestamp\`, and controller logs.\n2. Compare desired and observed state. Check selectors, readiness, requests, policies, node conditions, and recent changes.\n3. Make one bounded, reversible change.\n4. Confirm recovery from the user path: readiness, endpoints, response, and stable events.\n\n## Prevention\n\n- Alert on the leading indicator, not only the final outage.\n- Keep ownership and rollback instructions beside the manifest.\n- Test recovery in a disposable namespace or staging cluster.\n- Add a guardrail such as policy, quota, probe, backup, or admission validation.\n\nFurther reading: [${title}](${url}).`);
write(path.join(td,'manifest-guide.md'),`# ${n}. ${title}: walkthrough\n\nUse a namespaced example and server-side validation:\n\n\`\`\`powershell\nkubectl get all -n <namespace>\nkubectl describe <kind> <name> -n <namespace>\nkubectl apply --dry-run=server -f <manifest.yaml>\n\`\`\`\n\nSave the current YAML before a policy or controller change and verify selectors, owner references, and rollback.`);
write(path.join(td,'runbook.md'),`# ${n}. ${title}: runbook\n\n1. Announce the incident and record namespace, object, symptom, and timestamp.\n2. Inspect description, sorted events, owner, and dependencies.\n3. Protect availability or data first; pause an unsafe rollout or cordon a bad node when appropriate.\n4. Make the smallest reversible repair and watch the condition until stable.\n5. Re-test the user path, remove temporary mitigation, and document prevention.\n\nRollback: restore the last known-good manifest or revision, then verify no orphaned Pods, volumes, finalizers, or policies remain.`);
}}
console.log('created',chapters.reduce((n,c)=>n+c.topics.length,0),'topics');
