apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stock-observer
  namespace: k8s-learning-operations
subjects:
  - kind: ServiceAccount
    name: stock-observer
    namespace: k8s-learning-operations
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-observer
