apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookshop-locker
  namespace: k8s-learning-operations
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
