apiVersion: v1
kind: ResourceQuota
metadata:
  name: counter-budget
  namespace: k8s-learning-budgets
spec:
  hard:
    pods: '2'
    requests.cpu: 500m
    requests.memory: 256Mi
    limits.cpu: '1'
    limits.memory: 512Mi
