apiVersion: v1
kind: Service
metadata:
  name: reading-list
  namespace: k8s-learning-basics
  labels:
    app.kubernetes.io/name: reading-list
    app.kubernetes.io/part-of: core-components-project
spec:
  clusterIP: None
  selector:
    app: reading-list
  ports:
    - name: http
      port: 8080
      targetPort: http
