apiVersion: v1
kind: Namespace
metadata:
  name: k8s-learning-admission
  labels:
    app.kubernetes.io/part-of: kubernetes-learning-lab
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.30
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
