apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookshop-import
  namespace: k8s-learning-platform
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: bookshop-fake
    kind: SecretStore
  target:
    name: bookshop-imported
    creationPolicy: Owner
  data:
    - secretKey: practice
      remoteRef:
        key: /bookshop/practice
        version: v1
